Vagrant.configure("2") do |config|
  config.vm.define "manager" do |manager|
    manager.vm.box = "ubuntu/bionic64"
    manager.vm.hostname = "manager01"
    manager.vm.network "private_network", ip: "192.168.56.10"
    manager.vm.provision "file", source: "C:/Users/TIMUR/docker-compose.yml", destination: "/home/vagrant/docker-compose.yml"
    manager.vm.provision "file", source: "C:/Users/TIMUR/services", destination: "/home/vagrant/"
  end

  config.vm.define "node01" do |node01|
    node01.vm.box = "ubuntu/bionic64"
    node01.vm.hostname = "node01"
    node01.vm.network "private_network", ip: "192.168.56.11"
    node01.vm.network "forwarded_port", guest: 8080, host: 8080
  end

  config.vm.define "node02" do |node02|
    node02.vm.box = "ubuntu/bionic64"
    node02.vm.hostname = "node02"
    node02.vm.network "private_network", ip: "192.168.56.12"
  end
end
