Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/jammy64"

  config.vm.define "manager" do |manager|
    manager.vm.hostname = "manager"
    manager.vm.network "private_network", ip: "192.168.56.10"
    manager.vm.provision "file", source: "C:/Users/TIMUR/docker-compose.yml", destination: "/home/vagrant/docker-compose.yml"
    manager.vm.provision "file", source: "C:/Users/TIMUR/services", destination: "/home/vagrant/"
  end

  config.vm.define "consul_server" do |consul_server|
    consul_server.vm.hostname = "consulserver"
    consul_server.vm.network "private_network", ip: "192.168.56.20"
    consul_server.vm.network "forwarded_port", guest: 8500, host: 8500
  end

  config.vm.define "api" do |api|
    api.vm.hostname = "api"
    api.vm.network "private_network", ip: "192.168.56.21"
    api.vm.network "forwarded_port", guest: 8082, host: 8082
  end

  config.vm.define "db" do |db|
    db.vm.hostname = "db"
    db.vm.network "private_network", ip: "192.168.56.22"
  end
end
